DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS destination_tags;

CREATE TABLE destinations (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    place TEXT NOT NULL,
    country TEXT NOT NULL,
    climate TEXT NOT NULL,
    budget_min INTEGER NOT NULL,
    budget_max INTEGER NOT NULL,
    description_sentence TEXT NOT NULL,
    best_for TEXT NOT NULL,
    pace TEXT NOT NULL
);

INSERT INTO destinations (place, country, climate, budget_min, budget_max, description_sentence, best_for, pace) VALUES
('Paris', 'France', 'Temperate', 120, 350, 'Iconic cultural capital with world-class museums', 'Romantic and culture lovers', 'Moderate'),
('Rome', 'Italy', 'Temperate', 100, 300, 'Ancient city filled with historical landmarks', 'History enthusiasts', 'Moderate'),
('New York City', 'USA', 'Temperate', 150, 400, 'Dynamic global city with endless activities', 'Urban explorers', 'Packed'),
('Tokyo', 'Japan', 'Temperate', 120, 350, 'Blend of tradition and futuristic culture', 'Food lovers', 'Packed'),
('Bangkok', 'Thailand', 'Tropical', 40, 150, 'Affordable vibrant city with rich culture', 'Budget travelers', 'Packed'),
('Bali', 'Indonesia', 'Tropical', 50, 200, 'Tropical island with beaches and spirituality', 'Wellness seekers', 'Relaxed'),
('Santorini', 'Greece', 'Temperate', 150, 400, 'Famous for white houses and sunsets', 'Couples', 'Relaxed'),
('Cape Town', 'South Africa', 'Temperate', 80, 250, 'Diverse landscapes with adventure options', 'Nature lovers', 'Moderate'),
('Machu Picchu', 'Peru', 'Cold', 80, 250, 'Ancient Inca site in the Andes', 'Hikers', 'Packed'),
('Dubai', 'UAE', 'Desert', 150, 500, 'Luxury desert metropolis', 'Luxury travelers', 'Moderate'),
('Sydney', 'Australia', 'Temperate', 120, 350, 'Coastal city with iconic landmarks', 'Beach lovers', 'Moderate'),
('London', 'UK', 'Temperate', 120, 350, 'Historic city with global culture', 'First-time travelers', 'Packed'),
('Barcelona', 'Spain', 'Temperate', 90, 250, 'Vibrant city with Gaudi architecture', 'Young travelers', 'Moderate'),
('Amsterdam', 'Netherlands', 'Temperate', 100, 300, 'Charming canal city', 'Art lovers', 'Moderate'),
('Prague', 'Czech Republic', 'Temperate', 70, 200, 'Fairytale European city', 'Budget culture seekers', 'Moderate'),
('Vienna', 'Austria', 'Temperate', 110, 300, 'Elegant imperial city', 'Classical music lovers', 'Moderate'),
('Budapest', 'Hungary', 'Temperate', 60, 180, 'Affordable city with nightlife', 'Young travelers', 'Moderate'),
('Reykjavik', 'Iceland', 'Cold', 150, 400, 'Gateway to Icelandic nature', 'Nature photographers', 'Moderate'),
('Banff', 'Canada', 'Cold', 120, 350, 'Rocky Mountains scenery', 'Outdoor lovers', 'Moderate'),
('Queenstown', 'New Zealand', 'Temperate', 120, 350, 'Adventure capital of the world', 'Thrill seekers', 'Packed'),
('Maldives', 'Maldives', 'Tropical', 200, 800, 'Crystal-clear island paradise', 'Honeymooners', 'Relaxed'),
('Phuket', 'Thailand', 'Tropical', 50, 200, 'Beach destination with nightlife', 'Party + beach mix', 'Moderate'),
('Istanbul', 'Turkey', 'Temperate', 70, 220, 'Crossroads of Europe and Asia', 'Culture seekers', 'Moderate'),
('Rio de Janeiro', 'Brazil', 'Tropical', 80, 250, 'Energetic coastal city', 'Festive travelers', 'Packed'),
('Marrakech', 'Morocco', 'Desert', 60, 200, 'Exotic city with vibrant markets', 'Cultural immersion', 'Moderate'),
('Petra', 'Jordan', 'Desert', 90, 250, 'Ancient rock city', 'History lovers', 'Moderate'),
('Yellowstone', 'USA', 'Cold', 80, 250, 'Geothermal park with wildlife', 'Nature lovers', 'Moderate'),
('Kyoto', 'Japan', 'Temperate', 100, 300, 'Traditional Japanese culture hub', 'Culture lovers', 'Moderate'),
('Seoul', 'South Korea', 'Temperate', 90, 250, 'Modern meets tradition', 'Food & pop culture fans', 'Packed'),
('Singapore', 'Singapore', 'Tropical', 120, 350, 'Clean and futuristic city-state', 'Luxury urban travelers', 'Moderate'),
('Hong Kong', 'China', 'Tropical', 120, 350, 'Vertical city with vibrant energy', 'City lovers', 'Packed'),
('Los Angeles', 'USA', 'Temperate', 150, 400, 'Entertainment capital', 'Pop culture fans', 'Moderate'),
('Las Vegas', 'USA', 'Desert', 120, 400, 'Non-stop entertainment city', 'Party travelers', 'Packed'),
('Hawaii', 'USA', 'Tropical', 150, 400, 'Island paradise with nature', 'Beach + adventure', 'Relaxed'),
('Tulum', 'Mexico', 'Tropical', 100, 300, 'Trendy eco beach destination', 'Instagram travelers', 'Relaxed'),
('Cancun', 'Mexico', 'Tropical', 120, 350, 'All-inclusive beach hotspot', 'Party + relaxation', 'Moderate'),
('Vancouver', 'Canada', 'Temperate', 120, 300, 'City surrounded by nature', 'Outdoor lovers', 'Moderate'),
('San Francisco', 'USA', 'Temperate', 150, 400, 'Iconic coastal city', 'City explorers', 'Moderate'),
('Florence', 'Italy', 'Temperate', 100, 300, 'Renaissance art capital', 'Art lovers', 'Moderate'),
('Venice', 'Italy', 'Temperate', 120, 350, 'Unique canal city', 'Couples', 'Relaxed'),
('Athens', 'Greece', 'Temperate', 80, 220, 'Ancient Greek capital', 'History fans', 'Moderate'),
('Lisbon', 'Portugal', 'Temperate', 80, 220, 'Colorful coastal capital', 'Relaxed explorers', 'Moderate'),
('Porto', 'Portugal', 'Temperate', 70, 200, 'Charming riverside city', 'Wine lovers', 'Relaxed'),
('Edinburgh', 'UK', 'Cold', 100, 250, 'Historic Scottish capital', 'History lovers', 'Moderate'),
('Dublin', 'Ireland', 'Temperate', 100, 250, 'Friendly city with culture', 'Social travelers', 'Moderate'),
('Copenhagen', 'Denmark', 'Cold', 120, 300, 'Scandinavian design hub', 'Design lovers', 'Moderate'),
('Stockholm', 'Sweden', 'Cold', 120, 300, 'Archipelago capital', 'Nature + city mix', 'Moderate'),
('Hanoi', 'Vietnam', 'Tropical', 30, 120, 'Affordable cultural hub', 'Backpackers', 'Packed'),
('Ho Chi Minh City', 'Vietnam', 'Tropical', 30, 120, 'Energetic southern city', 'Budget explorers', 'Packed'),
('Bogota', 'Colombia', 'Temperate', 40, 150, 'Andean capital with culture', 'Urban explorers', 'Moderate'),
('Zermatt', 'Switzerland', 'Cold', 180, 500, 'Premium alpine resort with iconic Matterhorn views', 'Ski lovers', 'Moderate'),
('Interlaken', 'Switzerland', 'Temperate', 120, 350, 'Adventure hub between lakes and mountains', 'Thrill seekers', 'Packed'),
('Hallstatt', 'Austria', 'Temperate', 100, 250, 'Picturesque lakeside village', 'Photographers', 'Relaxed'),
('Salzburg', 'Austria', 'Temperate', 100, 280, 'Baroque city and Mozart''s birthplace', 'Classical culture fans', 'Moderate'),
('Nice', 'France', 'Temperate', 120, 300, 'Elegant French Riviera city', 'Beach + culture', 'Relaxed'),
('Monaco', 'Monaco', 'Temperate', 250, 800, 'Ultra-luxury coastal city-state', 'High-end travelers', 'Moderate'),
('Ibiza', 'Spain', 'Temperate', 120, 400, 'World-famous party island', 'Party lovers', 'Packed'),
('Valencia', 'Spain', 'Temperate', 80, 220, 'Modern meets tradition', 'Balanced travelers', 'Moderate'),
('Granada', 'Spain', 'Temperate', 70, 200, 'Historic Andalusian city', 'History lovers', 'Moderate'),
('Dubrovnik', 'Croatia', 'Temperate', 120, 300, 'Walled coastal medieval city', 'Game of Thrones fans', 'Moderate'),
('Split', 'Croatia', 'Temperate', 90, 250, 'Coastal city with Roman heritage', 'Summer travelers', 'Moderate'),
('Krakow', 'Poland', 'Temperate', 60, 180, 'Affordable historic city', 'Budget culture seekers', 'Moderate'),
('Warsaw', 'Poland', 'Temperate', 70, 200, 'Modern rebuilt capital', 'Urban explorers', 'Moderate'),
('Tallinn', 'Estonia', 'Cold', 80, 220, 'Fairytale Baltic city', 'Photographers', 'Relaxed'),
('Riga', 'Latvia', 'Cold', 70, 200, 'Art Nouveau capital', 'Architecture lovers', 'Moderate'),
('Vilnius', 'Lithuania', 'Cold', 70, 200, 'Charming Baltic capital', 'Quiet travelers', 'Relaxed'),
('Lviv', 'Ukraine', 'Temperate', 40, 120, 'Underrated cultural gem', 'Budget explorers', 'Relaxed'),
('Tbilisi', 'Georgia', 'Temperate', 40, 150, 'Unique blend of cultures', 'Food lovers', 'Relaxed'),
('Yerevan', 'Armenia', 'Temperate', 40, 140, 'Historic Caucasus capital', 'Culture seekers', 'Relaxed'),
('Baku', 'Azerbaijan', 'Desert', 70, 220, 'Fusion of old and futuristic', 'Urban explorers', 'Moderate'),
('Doha', 'Qatar', 'Desert', 120, 400, 'Modern Gulf city', 'Luxury culture', 'Moderate'),
('Muscat', 'Oman', 'Desert', 90, 250, 'Authentic Arabian destination', 'Nature lovers', 'Relaxed'),
('Kathmandu', 'Nepal', 'Temperate', 30, 120, 'Gateway to Himalayas', 'Trekkers', 'Packed'),
('Thimphu', 'Bhutan', 'Cold', 150, 300, 'Peaceful Himalayan kingdom', 'Spiritual travelers', 'Relaxed'),
('Colombo', 'Sri Lanka', 'Tropical', 40, 150, 'Gateway to Sri Lanka', 'Island explorers', 'Moderate'),
('Kandy', 'Sri Lanka', 'Tropical', 40, 140, 'Cultural hill city', 'Culture seekers', 'Relaxed'),
('Yangon', 'Myanmar', 'Tropical', 30, 120, 'Spiritual Southeast Asian city', 'Explorers', 'Moderate'),
('Luang Prabang', 'Laos', 'Tropical', 40, 150, 'UNESCO heritage town', 'Slow travelers', 'Relaxed'),
('Siem Reap', 'Cambodia', 'Tropical', 40, 150, 'Gateway to Angkor temples', 'History lovers', 'Moderate'),
('Ulaanbaatar', 'Mongolia', 'Cold', 50, 180, 'Nomadic culture experience', 'Adventure travelers', 'Moderate'),
('Almaty', 'Kazakhstan', 'Cold', 60, 200, 'Mountain city in Central Asia', 'Outdoor lovers', 'Moderate'),
('Tashkent', 'Uzbekistan', 'Desert', 60, 200, 'Silk Road capital', 'History fans', 'Moderate'),
('Samarkand', 'Uzbekistan', 'Desert', 60, 200, 'Iconic Silk Road city', 'Architecture lovers', 'Moderate'),
('Addis Ababa', 'Ethiopia', 'Temperate', 40, 150, 'African cultural hub', 'Explorers', 'Moderate'),
('Zanzibar', 'Tanzania', 'Tropical', 80, 250, 'Spice island paradise', 'Beach lovers', 'Relaxed'),
('Serengeti', 'Tanzania', 'Temperate', 200, 600, 'World-famous safari destination', 'Wildlife enthusiasts', 'Moderate'),
('Victoria Falls', 'Zimbabwe', 'Temperate', 100, 300, 'Massive waterfall spectacle', 'Adventure lovers', 'Moderate'),
('Namib Desert', 'Namibia', 'Desert', 100, 300, 'Iconic red sand dunes', 'Photographers', 'Relaxed'),
('Patagonia', 'Argentina/Chile', 'Cold', 120, 350, 'Remote wilderness region', 'Serious hikers', 'Moderate'),
('Cusco', 'Peru', 'Cold', 70, 200, 'Historic Inca capital', 'Culture + hiking', 'Moderate'),
('Santiago', 'Chile', 'Temperate', 80, 250, 'Modern capital near Andes', 'Urban explorers', 'Moderate'),
('Valparaiso', 'Chile', 'Temperate', 70, 200, 'Colorful artistic port city', 'Art lovers', 'Relaxed'),
('Quito', 'Ecuador', 'Temperate', 50, 180, 'High-altitude capital', 'Culture seekers', 'Moderate'),
('Galapagos Islands', 'Ecuador', 'Tropical', 250, 700, 'Unique wildlife ecosystem', 'Nature enthusiasts', 'Moderate'),
('La Paz', 'Bolivia', 'Cold', 40, 150, 'World''s highest capital city', 'Adventurers', 'Packed'),
('Montevideo', 'Uruguay', 'Temperate', 80, 220, 'Laid-back capital', 'Slow travelers', 'Relaxed'),
('Punta del Este', 'Uruguay', 'Temperate', 120, 350, 'Upscale beach resort', 'Luxury beachgoers', 'Moderate'),
('Reykjanes', 'Iceland', 'Cold', 150, 400, 'Volcanic landscapes near Reykjavik', 'Nature explorers', 'Moderate'),
('Faroe Islands', 'Denmark', 'Cold', 120, 350, 'Remote North Atlantic islands', 'Photographers', 'Relaxed'),
('Greenland', 'Denmark', 'Cold', 200, 600, 'Extreme Arctic destination', 'Extreme adventurers', 'Moderate'),
('Bruges', 'Belgium', 'Temperate', 100, 250, 'Charming medieval canal city', 'Romantic getaways', 'Relaxed'),
('Ghent', 'Belgium', 'Temperate', 90, 230, 'Lively historic university city', 'Young travelers', 'Moderate'),
('Luxembourg City', 'Luxembourg', 'Temperate', 120, 300, 'Small but scenic capital', 'Quiet explorers', 'Relaxed'),
('Andorra la Vella', 'Andorra', 'Cold', 90, 250, 'Mountain shopping destination', 'Ski + shopping', 'Moderate'),
('Chamonix', 'France', 'Cold', 150, 400, 'Famous Mont Blanc resort', 'Alpine adventurers', 'Moderate'),
('Bordeaux', 'France', 'Temperate', 100, 280, 'Wine capital of France', 'Wine lovers', 'Relaxed'),
('Lyon', 'France', 'Temperate', 100, 250, 'France''s culinary capital', 'Food enthusiasts', 'Moderate'),
('Marseille', 'France', 'Temperate', 90, 220, 'Mediterranean port city', 'Coastal travelers', 'Moderate'),
('Naples', 'Italy', 'Temperate', 80, 220, 'Authentic Italian culture hub', 'Food lovers', 'Packed'),
('Milan', 'Italy', 'Temperate', 120, 350, 'Global fashion capital', 'Shopping lovers', 'Moderate'),
('Turin', 'Italy', 'Temperate', 90, 250, 'Elegant northern Italian city', 'Culture seekers', 'Moderate'),
('Siena', 'Italy', 'Temperate', 90, 250, 'Tuscan medieval gem', 'Slow travelers', 'Relaxed'),
('Palermo', 'Italy', 'Temperate', 70, 200, 'Vibrant Sicilian capital', 'Food explorers', 'Moderate'),
('Valletta', 'Malta', 'Temperate', 90, 250, 'Compact fortified capital', 'History lovers', 'Relaxed'),
('Reykjavik Region', 'Iceland', 'Cold', 150, 400, 'Access to Iceland''s highlights', 'Nature seekers', 'Moderate'),
('Oslo', 'Norway', 'Cold', 150, 350, 'Scandinavian waterfront capital', 'Design lovers', 'Moderate'),
('Bergen', 'Norway', 'Cold', 130, 320, 'Gateway to fjords', 'Nature lovers', 'Moderate'),
('Helsinki', 'Finland', 'Cold', 120, 300, 'Nordic design hub', 'Design enthusiasts', 'Moderate'),
('Tampere', 'Finland', 'Cold', 100, 250, 'Laid-back Finnish city', 'Relaxation seekers', 'Relaxed'),
('Gdansk', 'Poland', 'Temperate', 70, 200, 'Baltic coastal gem', 'History lovers', 'Relaxed'),
('Brasov', 'Romania', 'Cold', 60, 180, 'Gateway to Transylvania', 'Adventure + history', 'Moderate'),
('Bucharest', 'Romania', 'Temperate', 60, 180, 'Dynamic Eastern capital', 'Urban explorers', 'Moderate'),
('Sofia', 'Bulgaria', 'Temperate', 50, 150, 'Affordable European capital', 'Budget travelers', 'Moderate'),
('Belgrade', 'Serbia', 'Temperate', 60, 180, 'Party capital of Balkans', 'Nightlife lovers', 'Packed'),
('Sarajevo', 'Bosnia and Herzegovina', 'Temperate', 50, 150, 'Cultural crossroads city', 'History seekers', 'Moderate'),
('Skopje', 'North Macedonia', 'Temperate', 50, 150, 'Unique Balkan capital', 'Curious travelers', 'Relaxed'),
('Podgorica', 'Montenegro', 'Temperate', 60, 180, 'Quiet Balkan capital', 'Nature lovers', 'Relaxed'),
('Kotor', 'Montenegro', 'Temperate', 90, 250, 'Stunning bay town', 'Photographers', 'Relaxed'),
('Tirana', 'Albania', 'Temperate', 50, 150, 'Colorful emerging destination', 'Budget explorers', 'Moderate'),
('Accra', 'Ghana', 'Tropical', 50, 180, 'West African coastal capital', 'Culture seekers', 'Moderate'),
('Dakar', 'Senegal', 'Tropical', 60, 200, 'Vibrant cultural hub', 'Music lovers', 'Moderate'),
('Abidjan', 'Ivory Coast', 'Tropical', 60, 200, 'Lively economic capital', 'Nightlife seekers', 'Packed'),
('Nairobi', 'Kenya', 'Temperate', 80, 250, 'Safari gateway city', 'Wildlife lovers', 'Moderate'),
('Mombasa', 'Kenya', 'Tropical', 80, 250, 'Indian Ocean coastal city', 'Beach travelers', 'Relaxed'),
('Antananarivo', 'Madagascar', 'Tropical', 50, 150, 'Gateway to Madagascar biodiversity', 'Nature lovers', 'Moderate'),
('Windhoek', 'Namibia', 'Desert', 80, 250, 'Base for Namibian adventures', 'Explorers', 'Moderate'),
('Perth', 'Australia', 'Temperate', 120, 300, 'Remote sunny coastal city', 'Beach lovers', 'Relaxed'),
('Adelaide', 'Australia', 'Temperate', 110, 280, 'Wine and festival city', 'Food & wine', 'Relaxed'),
('Darwin', 'Australia', 'Tropical', 100, 250, 'Gateway to the Outback', 'Adventure seekers', 'Moderate'),
('Hobart', 'Australia', 'Cold', 100, 250, 'Tasmania''s cultural hub', 'Art lovers', 'Relaxed'),
('Suva', 'Fiji', 'Tropical', 80, 250, 'Pacific island capital', 'Beach relaxation', 'Relaxed'),
('Apia', 'Samoa', 'Tropical', 70, 220, 'Authentic island escape', 'Quiet beach lovers', 'Relaxed'),
('Port Vila', 'Vanuatu', 'Tropical', 80, 250, 'Adventure island destination', 'Divers', 'Moderate'),
('Noumea', 'New Caledonia', 'Tropical', 120, 350, 'French-style Pacific island', 'Luxury beach', 'Relaxed'),
('Anchorage', 'USA', 'Cold', 120, 300, 'Alaska''s wilderness hub', 'Nature explorers', 'Moderate'),
('Juneau', 'USA', 'Cold', 130, 320, 'Remote Alaskan capital', 'Wildlife lovers', 'Moderate'),
('Quebec City', 'Canada', 'Cold', 120, 300, 'European-style Canadian city', 'Romantic travelers', 'Moderate'),
('Halifax', 'Canada', 'Cold', 100, 250, 'Coastal maritime city', 'Seafood lovers', 'Relaxed'),
('Winnipeg', 'Canada', 'Cold', 80, 220, 'Prairie cultural center', 'Museum visitors', 'Moderate'),
('Asheville', 'USA', 'Temperate', 90, 250, 'Creative mountain town in North Carolina', 'Nature + art lovers', 'Relaxed'),
('Sedona', 'USA', 'Desert', 120, 350, 'Red rock desert landscapes', 'Wellness travelers', 'Relaxed'),
('Santa Fe', 'USA', 'Desert', 120, 300, 'Southwestern art hub', 'Art lovers', 'Relaxed'),
('Nashville', 'USA', 'Temperate', 120, 300, 'Country music capital', 'Music fans', 'Packed'),
('Austin', 'USA', 'Temperate', 100, 280, 'Trendy Texas city', 'Young travelers', 'Packed'),
('Savannah', 'USA', 'Temperate', 100, 250, 'Charming southern city', 'Romantic travelers', 'Relaxed'),
('Charleston', 'USA', 'Temperate', 120, 300, 'Historic coastal city', 'Culture + food', 'Relaxed'),
('Tampa', 'USA', 'Tropical', 100, 250, 'Florida coastal city', 'Beach travelers', 'Moderate'),
('Cartagena', 'Colombia', 'Tropical', 80, 250, 'Colorful Caribbean city', 'Culture + beach', 'Moderate'),
('Medellin', 'Colombia', 'Temperate', 50, 180, 'Innovative Colombian city', 'Urban explorers', 'Moderate'),
('Salvador', 'Brazil', 'Tropical', 70, 200, 'Afro-Brazilian culture hub', 'Culture seekers', 'Moderate'),
('Florianopolis', 'Brazil', 'Tropical', 80, 250, 'Island with many beaches', 'Surfers', 'Relaxed'),
('Punta Cana', 'Dominican Republic', 'Tropical', 120, 350, 'All-inclusive beach destination', 'Beach relaxation', 'Relaxed'),
('Havana', 'Cuba', 'Tropical', 70, 200, 'Vintage Caribbean capital', 'Culture lovers', 'Moderate'),
('San Jose', 'Costa Rica', 'Tropical', 70, 200, 'Gateway to Costa Rica nature', 'Eco travelers', 'Moderate'),
('Panama City', 'Panama', 'Tropical', 80, 220, 'Modern city with historic core', 'Urban travelers', 'Moderate'),
('Guatemala City', 'Guatemala', 'Tropical', 50, 150, 'Central American capital', 'Budget explorers', 'Moderate'),
('Antigua', 'Guatemala', 'Temperate', 60, 180, 'Colonial UNESCO town', 'Photographers', 'Relaxed'),
('Manila', 'Philippines', 'Tropical', 50, 180, 'Bustling Asian capital', 'City explorers', 'Packed'),
('Cebu', 'Philippines', 'Tropical', 60, 200, 'Island adventure hub', 'Divers', 'Moderate'),
('Boracay', 'Philippines', 'Tropical', 80, 250, 'White sand beach island', 'Beach lovers', 'Relaxed'),
('Sapporo', 'Japan', 'Cold', 100, 280, 'Northern Japan city', 'Winter travelers', 'Moderate'),
('Fukuoka', 'Japan', 'Temperate', 90, 250, 'Food capital of Japan', 'Food lovers', 'Moderate'),
('Busan', 'South Korea', 'Temperate', 80, 220, 'Coastal Korean city', 'Beach + food', 'Moderate'),
('Da Nang', 'Vietnam', 'Tropical', 40, 150, 'Coastal Vietnamese city', 'Beach travelers', 'Relaxed'),
('Chiang Mai', 'Thailand', 'Tropical', 40, 150, 'Northern Thai cultural hub', 'Digital nomads', 'Relaxed'),
('Penang', 'Malaysia', 'Tropical', 40, 150, 'Food paradise island', 'Foodies', 'Moderate'),
('Kuala Lumpur', 'Malaysia', 'Tropical', 60, 200, 'Modern Southeast Asian capital', 'City lovers', 'Moderate'),
('Jakarta', 'Indonesia', 'Tropical', 50, 180, 'Busy megacity', 'Urban travelers', 'Packed'),
('Yogyakarta', 'Indonesia', 'Tropical', 40, 150, 'Cultural heart of Java', 'Culture lovers', 'Moderate'),
('Tehran', 'Iran', 'Desert', 50, 150, 'Historic Persian capital', 'History lovers', 'Moderate'),
('Isfahan', 'Iran', 'Desert', 50, 150, 'One of Iran''s most beautiful cities', 'Architecture lovers', 'Relaxed'),
('Shiraz', 'Iran', 'Desert', 50, 150, 'City of poets and gardens', 'Culture seekers', 'Relaxed'),
('Amman', 'Jordan', 'Desert', 80, 220, 'Modern Middle Eastern capital', 'Urban explorers', 'Moderate'),
('Beirut', 'Lebanon', 'Temperate', 90, 250, 'Vibrant Mediterranean city', 'Nightlife lovers', 'Packed'),
('Tunis', 'Tunisia', 'Desert', 60, 180, 'Historic North African capital', 'Culture seekers', 'Moderate'),
('Algiers', 'Algeria', 'Temperate', 60, 180, 'Mediterranean capital', 'History lovers', 'Moderate'),
('Cape Verde', 'Cape Verde', 'Tropical', 80, 250, 'Atlantic island escape', 'Beach relaxation', 'Relaxed'),
('Seychelles', 'Seychelles', 'Tropical', 200, 600, 'Exclusive island paradise', 'Luxury beach', 'Relaxed'),
('Mauritius', 'Mauritius', 'Tropical', 120, 400, 'Indian Ocean island', 'Honeymooners', 'Relaxed'),
('Rotorua', 'New Zealand', 'Temperate', 100, 280, 'Geothermal wonderland', 'Nature explorers', 'Moderate'),
('Christchurch', 'New Zealand', 'Temperate', 100, 280, 'Garden city', 'Relaxed explorers', 'Moderate'),
('Innsbruck', 'Austria', 'Cold', 120, 300, 'Alpine sports hub', 'Ski lovers', 'Moderate'),
('Geneva', 'Switzerland', 'Temperate', 180, 450, 'International lakeside city', 'Luxury travelers', 'Moderate'),
('Lausanne', 'Switzerland', 'Temperate', 150, 350, 'Charming lakeside city', 'Relaxation seekers', 'Relaxed'),
('Basel', 'Switzerland', 'Temperate', 150, 350, 'Swiss cultural capital', 'Art lovers', 'Moderate'),
('Zurich', 'Switzerland', 'Temperate', 180, 450, 'Financial and cultural hub', 'Luxury city travel', 'Moderate'),
('Ljubljana', 'Slovenia', 'Temperate', 80, 220, 'Green European capital', 'Eco travelers', 'Relaxed'),
('Lake Bled', 'Slovenia', 'Temperate', 90, 250, 'Fairytale alpine lake', 'Romantic nature', 'Relaxed'),
('Mostar', 'Bosnia and Herzegovina', 'Temperate', 50, 150, 'Iconic Ottoman bridge town', 'Photographers', 'Relaxed'),
('Kigali', 'Rwanda', 'Temperate', 60, 180, 'Clean and rapidly developing African capital', 'Urban explorers', 'Moderate'),
('Gisenyi', 'Rwanda', 'Tropical', 70, 200, 'Lakeside retreat on Lake Kivu', 'Relaxation seekers', 'Relaxed'),
('Bujumbura', 'Burundi', 'Tropical', 50, 150, 'Quiet lakeside capital', 'Offbeat travelers', 'Relaxed'),
('Lilongwe', 'Malawi', 'Tropical', 40, 140, 'Gateway to Malawi nature', 'Budget explorers', 'Moderate'),
('Maputo', 'Mozambique', 'Tropical', 60, 180, 'Coastal African capital', 'Culture + beach', 'Moderate'),
('Tofino', 'Canada', 'Temperate', 120, 320, 'Wild Pacific coastline town', 'Nature lovers', 'Relaxed'),
('Whistler', 'Canada', 'Cold', 150, 400, 'Top ski resort destination', 'Winter sports', 'Moderate'),
('Banff Town', 'Canada', 'Cold', 130, 350, 'Scenic Rockies town', 'Outdoor lovers', 'Moderate'),
('Canmore', 'Canada', 'Cold', 120, 300, 'Quieter alternative to Banff', 'Nature seekers', 'Relaxed'),
('Tromso', 'Norway', 'Cold', 150, 350, 'Arctic adventure city', 'Aurora hunters', 'Moderate'),
('Rovaniemi', 'Finland', 'Cold', 140, 320, 'Lapland winter wonderland', 'Winter families', 'Moderate'),
('Nuuk', 'Greenland', 'Cold', 200, 600, 'Remote Arctic capital', 'Extreme explorers', 'Moderate'),
('Svalbard', 'Norway', 'Cold', 250, 700, 'Polar wilderness archipelago', 'Wildlife enthusiasts', 'Moderate'),
('Azores', 'Portugal', 'Temperate', 100, 250, 'Volcanic island group', 'Nature lovers', 'Relaxed'),
('Madeira', 'Portugal', 'Temperate', 90, 220, 'Island of eternal spring', 'Hikers', 'Relaxed'),
('Corsica', 'France', 'Temperate', 100, 280, 'Mountainous Mediterranean island', 'Adventure + beach', 'Moderate'),
('Sardinia', 'Italy', 'Temperate', 120, 320, 'Crystal-clear Mediterranean island', 'Luxury beach', 'Relaxed'),
('Menorca', 'Spain', 'Temperate', 100, 250, 'Quiet Balearic island', 'Peaceful beach', 'Relaxed'),
('Mallorca', 'Spain', 'Temperate', 100, 280, 'Diverse island landscapes', 'Active travelers', 'Moderate'),
('Goa', 'India', 'Tropical', 40, 150, 'India''s beach capital', 'Party + beach', 'Moderate'),
('Kerala', 'India', 'Tropical', 40, 150, 'Tropical backwater region', 'Wellness seekers', 'Relaxed'),
('Jaipur', 'India', 'Desert', 50, 180, 'Pink City of India', 'Culture lovers', 'Moderate'),
('Udaipur', 'India', 'Temperate', 50, 180, 'Romantic lake city', 'Couples', 'Relaxed'),
('Lahore', 'Pakistan', 'Temperate', 40, 140, 'Cultural capital of Pakistan', 'Food lovers', 'Moderate'),
('Karachi', 'Pakistan', 'Tropical', 50, 150, 'Mega coastal city', 'Urban explorers', 'Packed'),
('Dhaka', 'Bangladesh', 'Tropical', 40, 120, 'Dense cultural capital', 'Budget explorers', 'Packed'),
('Kathmandu Valley', 'Nepal', 'Temperate', 30, 120, 'Cultural Himalayan region', 'Trekkers', 'Moderate'),
('Paro', 'Bhutan', 'Cold', 150, 300, 'Scenic Himalayan valley', 'Spiritual travelers', 'Relaxed'),
('Lhasa', 'Tibet', 'Cold', 120, 300, 'Spiritual Tibetan capital', 'Cultural explorers', 'Moderate'),
('Chengdu', 'China', 'Temperate', 60, 200, 'Home of giant pandas', 'Wildlife lovers', 'Moderate'),
('Guilin', 'China', 'Temperate', 60, 200, 'Karst mountain landscapes', 'Photographers', 'Relaxed'),
('Zhangjiajie', 'China', 'Temperate', 70, 220, 'Avatar-like rock formations', 'Nature explorers', 'Moderate'),
('Harbin', 'China', 'Cold', 70, 220, 'Famous winter festival city', 'Winter travelers', 'Moderate'),
('Ushuaia', 'Argentina', 'Cold', 120, 350, 'World''s southernmost city', 'Extreme adventurers', 'Moderate'),
('Bariloche', 'Argentina', 'Cold', 100, 280, 'Patagonian alpine town', 'Nature lovers', 'Moderate'),
('Mendoza', 'Argentina', 'Temperate', 90, 250, 'Wine region near Andes', 'Wine lovers', 'Relaxed'),
('Cusco Region', 'Peru', 'Cold', 70, 200, 'Historic Andean region', 'Trekkers', 'Moderate'),
('Arequipa', 'Peru', 'Temperate', 60, 180, 'White city of Peru', 'Culture seekers', 'Relaxed'),
('La Serena', 'Chile', 'Temperate', 70, 200, 'Coastal Chilean city', 'Beach lovers', 'Relaxed'),
('Pucon', 'Chile', 'Temperate', 80, 220, 'Adventure town near volcano', 'Thrill seekers', 'Moderate'),
('Sucre', 'Bolivia', 'Temperate', 50, 150, 'Colonial capital', 'History lovers', 'Relaxed'),
('Oruro', 'Bolivia', 'Cold', 50, 150, 'Famous for cultural festivals', 'Festival lovers', 'Moderate'),
('Asuncion', 'Paraguay', 'Tropical', 60, 180, 'Laid-back capital', 'Slow travelers', 'Moderate'),
('Recife', 'Brazil', 'Tropical', 80, 220, 'Northeastern beach city', 'Beach travelers', 'Moderate'),
('Fortaleza', 'Brazil', 'Tropical', 80, 220, 'Sunny coastal city', 'Party beach', 'Moderate'),
('Natal', 'Brazil', 'Tropical', 80, 220, 'Dune-filled coastline', 'Nature + beach', 'Relaxed'),
('Aruba', 'Netherlands', 'Tropical', 150, 400, 'Caribbean luxury island', 'Luxury beach', 'Relaxed'),
('Curacao', 'Netherlands', 'Tropical', 120, 350, 'Colorful Caribbean island', 'Divers', 'Relaxed'),
('Bonaire', 'Netherlands', 'Tropical', 120, 350, 'Top diving destination', 'Divers', 'Relaxed');


CREATE TABLE destination_tags (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    destination_id INTEGER NOT NULL,
    tag_type TEXT NOT NULL,
    tag_value TEXT NOT NULL,
    FOREIGN KEY (destination_id) REFERENCES destinations(id)
);

INSERT INTO destination_tags (destination_id, tag_type, tag_value) VALUES
(1,'style','Luxury Traveler'),(1,'style','Cultural Explorer'),(1,'interest','Art & Museums'),(1,'interest','Food & Cuisine'),(1,'interest','Architecture'),(1,'interest','History'),(1,'interest','Shopping'),(1,'activity','Visit museums, cafes, landmarks'),(1,'accommodation','Hotels & boutique stays'),
(2,'style','Cultural Explorer'),(2,'interest','History'),(2,'interest','Architecture'),(2,'interest','Food & Cuisine'),(2,'interest','Art & Museums'),(2,'activity','Explore ruins, Vatican tours'),(2,'accommodation','Hotels & apartments'),
(3,'style','Luxury Traveler'),(3,'style','Cultural Explorer'),(3,'interest','Shopping'),(3,'interest','Nightlife'),(3,'interest','Art & Museums'),(3,'interest','Architecture'),(3,'activity','Broadway, skyline views'),(3,'accommodation','Hotels'),
(4,'style','Cultural Explorer'),(4,'interest','Food & Cuisine'),(4,'interest','Shopping'),(4,'interest','Art & Museums'),(4,'interest','Architecture'),(4,'activity','Temples, food tours'),(4,'accommodation','Hotels & ryokan'),
(5,'style','Budget Backpacker'),(5,'style','Cultural Explorer'),(5,'interest','Food & Cuisine'),(5,'interest','Nightlife'),(5,'interest','Shopping'),(5,'interest','Architecture'),(5,'activity','Street food, temples'),(5,'accommodation','Hostels & hotels'),
(6,'style','Relaxation Focused'),(6,'style','Adventure Seeker'),(6,'interest','Beaches'),(6,'interest','Water Sports'),(6,'interest','Hiking'),(6,'interest','Photography'),(6,'activity','Surfing, temples, yoga'),(6,'accommodation','Villas & resorts'),
(7,'style','Luxury Traveler'),(7,'style','Relaxation Focused'),(7,'interest','Beaches'),(7,'interest','Photography'),(7,'interest','Food & Cuisine'),(7,'activity','Sunset views, sailing'),(7,'accommodation','Boutique hotels'),
(8,'style','Adventure Seeker'),(8,'style','Cultural Explorer'),(8,'interest','Mountains'),(8,'interest','Beaches'),(8,'interest','Wildlife'),(8,'interest','Photography'),(8,'activity','Hiking, safaris'),(8,'accommodation','Hotels & lodges'),
(9,'style','Adventure Seeker'),(9,'style','Cultural Explorer'),(9,'interest','History'),(9,'interest','Hiking'),(9,'interest','Mountains'),(9,'interest','Photography'),(9,'activity','Trekking, ruins'),(9,'accommodation','Lodges'),
(10,'style','Luxury Traveler'),(10,'interest','Shopping'),(10,'interest','Beaches'),(10,'interest','Architecture'),(10,'activity','Shopping malls, desert safari'),(10,'accommodation','Luxury hotels'),
(11,'style','Relaxation Focused'),(11,'style','Adventure Seeker'),(11,'interest','Beaches'),(11,'interest','Water Sports'),(11,'interest','Photography'),(11,'activity','Surfing, harbor tours'),(11,'accommodation','Hotels'),
(12,'style','Cultural Explorer'),(12,'interest','History'),(12,'interest','Art & Museums'),(12,'interest','Shopping'),(12,'interest','Architecture'),(12,'activity','Museums, sightseeing'),(12,'accommodation','Hotels'),
(13,'style','Cultural Explorer'),(13,'style','Relaxation Focused'),(13,'interest','Beaches'),(13,'interest','Architecture'),(13,'interest','Food & Cuisine'),(13,'interest','Nightlife'),(13,'activity','Beach + city mix'),(13,'accommodation','Hotels'),
(14,'style','Cultural Explorer'),(14,'interest','Art & Museums'),(14,'interest','Architecture'),(14,'interest','Shopping'),(14,'activity','Canals, museums'),(14,'accommodation','Hotels'),
(15,'style','Budget Backpacker'),(15,'style','Cultural Explorer'),(15,'interest','History'),(15,'interest','Architecture'),(15,'interest','Photography'),(15,'activity','Castle visits'),(15,'accommodation','Hotels'),
(16,'style','Cultural Explorer'),(16,'interest','Art & Museums'),(16,'interest','History'),(16,'interest','Architecture'),(16,'activity','Concerts, museums'),(16,'accommodation','Hotels'),
(17,'style','Budget Backpacker'),(17,'style','Cultural Explorer'),(17,'interest','Architecture'),(17,'interest','Nightlife'),(17,'interest','History'),(17,'activity','Thermal baths'),(17,'accommodation','Hotels'),
(18,'style','Adventure Seeker'),(18,'interest','Mountains'),(18,'interest','Wildlife'),(18,'interest','Photography'),(18,'activity','Northern lights, glaciers'),(18,'accommodation','Hotels'),
(19,'style','Adventure Seeker'),(19,'interest','Mountains'),(19,'interest','Hiking'),(19,'interest','Wildlife'),(19,'interest','Photography'),(19,'activity','Skiing, hiking'),(19,'accommodation','Lodges'),
(20,'style','Adventure Seeker'),(20,'interest','Mountains'),(20,'interest','Water Sports'),(20,'interest','Hiking'),(20,'activity','Bungee, skiing'),(20,'accommodation','Hotels'),
(21,'style','Luxury Traveler'),(21,'style','Relaxation Focused'),(21,'interest','Beaches'),(21,'interest','Water Sports'),(21,'activity','Snorkeling, resorts'),(21,'accommodation','Luxury resorts'),
(22,'style','Relaxation Focused'),(22,'style','Adventure Seeker'),(22,'interest','Beaches'),(22,'interest','Nightlife'),(22,'interest','Water Sports'),(22,'activity','Island hopping'),(22,'accommodation','Hotels'),
(23,'style','Cultural Explorer'),(23,'interest','History'),(23,'interest','Architecture'),(23,'interest','Food & Cuisine'),(23,'interest','Shopping'),(23,'activity','Mosques, bazaars'),(23,'accommodation','Hotels'),
(24,'style','Adventure Seeker'),(24,'style','Relaxation Focused'),(24,'interest','Beaches'),(24,'interest','Nightlife'),(24,'interest','Mountains'),(24,'activity','Beach, carnival'),(24,'accommodation','Hotels'),
(25,'style','Cultural Explorer'),(25,'interest','Architecture'),(25,'interest','Food & Cuisine'),(25,'activity','Souks, desert tours'),(25,'accommodation','Riads'),
(26,'style','Adventure Seeker'),(26,'style','Cultural Explorer'),(26,'interest','History'),(26,'interest','Photography'),(26,'activity','Explore ruins'),(26,'accommodation','Hotels'),
(27,'style','Adventure Seeker'),(27,'interest','Wildlife'),(27,'interest','Hiking'),(27,'interest','Photography'),(27,'activity','Geysers, camping'),(27,'accommodation','Lodges'),
(28,'style','Cultural Explorer'),(28,'interest','History'),(28,'interest','Art & Museums'),(28,'interest','Photography'),(28,'activity','Temples, tea ceremonies'),(28,'accommodation','Ryokan'),
(29,'style','Cultural Explorer'),(29,'interest','Shopping'),(29,'interest','Nightlife'),(29,'interest','Food & Cuisine'),(29,'activity','Street food, palaces'),(29,'accommodation','Hotels'),
(30,'style','Luxury Traveler'),(30,'style','Cultural Explorer'),(30,'interest','Shopping'),(30,'interest','Food & Cuisine'),(30,'interest','Architecture'),(30,'activity','Gardens, malls'),(30,'accommodation','Hotels'),
(31,'style','Cultural Explorer'),(31,'interest','Shopping'),(31,'interest','Nightlife'),(31,'interest','Food & Cuisine'),(31,'activity','Skyline, markets'),(31,'accommodation','Hotels'),
(32,'style','Luxury Traveler'),(32,'style','Relaxation Focused'),(32,'interest','Beaches'),(32,'interest','Shopping'),(32,'interest','Nightlife'),(32,'activity','Hollywood tours'),(32,'accommodation','Hotels'),
(33,'style','Luxury Traveler'),(33,'interest','Nightlife'),(33,'interest','Shopping'),(33,'activity','Casinos, shows'),(33,'accommodation','Hotels'),
(34,'style','Relaxation Focused'),(34,'style','Adventure Seeker'),(34,'interest','Beaches'),(34,'interest','Water Sports'),(34,'interest','Mountains'),(34,'activity','Surfing, volcanoes'),(34,'accommodation','Resorts'),
(35,'style','Relaxation Focused'),(35,'interest','Beaches'),(35,'interest','Photography'),(35,'interest','Food & Cuisine'),(35,'activity','Beach clubs, ruins'),(35,'accommodation','Boutique hotels'),
(36,'style','Relaxation Focused'),(36,'interest','Beaches'),(36,'interest','Nightlife'),(36,'interest','Water Sports'),(36,'activity','Resorts, parties'),(36,'accommodation','Resorts'),
(37,'style','Adventure Seeker'),(37,'interest','Mountains'),(37,'interest','Water Sports'),(37,'interest','Photography'),(37,'activity','Skiing, hiking'),(37,'accommodation','Hotels'),
(38,'style','Cultural Explorer'),(38,'interest','Architecture'),(38,'interest','Food & Cuisine'),(38,'interest','Photography'),(38,'activity','Golden Gate, tech tours'),(38,'accommodation','Hotels'),
(39,'style','Cultural Explorer'),(39,'interest','Art & Museums'),(39,'interest','History'),(39,'interest','Architecture'),(39,'activity','Museums, food tours'),(39,'accommodation','Hotels'),
(40,'style','Luxury Traveler'),(40,'interest','Architecture'),(40,'interest','Photography'),(40,'activity','Gondola rides'),(40,'accommodation','Hotels'),
(41,'style','Cultural Explorer'),(41,'interest','History'),(41,'interest','Architecture'),(41,'activity','Acropolis visits'),(41,'accommodation','Hotels'),
(42,'style','Cultural Explorer'),(42,'interest','Food & Cuisine'),(42,'interest','Architecture'),(42,'interest','Photography'),(42,'activity','Trams, viewpoints'),(42,'accommodation','Hotels'),
(43,'style','Cultural Explorer'),(43,'interest','Food & Cuisine'),(43,'interest','Photography'),(43,'activity','Wine tasting'),(43,'accommodation','Hotels'),
(44,'style','Cultural Explorer'),(44,'interest','History'),(44,'interest','Architecture'),(44,'activity','Castle tours'),(44,'accommodation','Hotels'),
(45,'style','Cultural Explorer'),(45,'interest','Nightlife'),(45,'interest','History'),(45,'activity','Pubs, museums'),(45,'accommodation','Hotels'),
(46,'style','Cultural Explorer'),(46,'interest','Architecture'),(46,'interest','Food & Cuisine'),(46,'interest','Shopping'),(46,'activity','Cycling, design'),(46,'accommodation','Hotels'),
(47,'style','Cultural Explorer'),(47,'interest','Architecture'),(47,'interest','Photography'),(47,'activity','Islands, museums'),(47,'accommodation','Hotels'),
(48,'style','Budget Backpacker'),(48,'style','Cultural Explorer'),(48,'interest','Food & Cuisine'),(48,'interest','History'),(48,'activity','Street food, old quarter'),(48,'accommodation','Hostels'),
(49,'style','Budget Backpacker'),(49,'interest','Food & Cuisine'),(49,'interest','Nightlife'),(49,'activity','Markets, nightlife'),(49,'accommodation','Hostels'),
(50,'style','Cultural Explorer'),(50,'interest','Art & Museums'),(50,'interest','History'),(50,'activity','Museums, city tours'),(50,'accommodation','Hotels'),
(51,'style','Luxury Traveler'),(51,'style','Adventure Seeker'),(51,'interest','Mountains'),(51,'interest','Hiking'),(51,'interest','Photography'),(51,'activity','Skiing, alpine hiking'),(51,'accommodation','Luxury hotels & chalets'),
(52,'style','Adventure Seeker'),(52,'interest','Mountains'),(52,'interest','Water Sports'),(52,'interest','Hiking'),(52,'interest','Photography'),(52,'activity','Paragliding, lake sports'),(52,'accommodation','Hotels & hostels'),
(53,'style','Cultural Explorer'),(53,'style','Relaxation Focused'),(53,'interest','Photography'),(53,'interest','Mountains'),(53,'interest','History'),(53,'activity','Lake walks, sightseeing'),(53,'accommodation','Boutique hotels'),
(54,'style','Cultural Explorer'),(54,'interest','History'),(54,'interest','Architecture'),(54,'interest','Art & Museums'),(54,'activity','Music tours, old town visits'),(54,'accommodation','Hotels'),
(55,'style','Relaxation Focused'),(55,'style','Luxury Traveler'),(55,'interest','Beaches'),(55,'interest','Food & Cuisine'),(55,'interest','Photography'),(55,'activity','Beach time, promenades'),(55,'accommodation','Hotels'),
(56,'style','Luxury Traveler'),(56,'interest','Shopping'),(56,'interest','Nightlife'),(56,'interest','Beaches'),(56,'activity','Casinos, yachting'),(56,'accommodation','Luxury hotels'),
(57,'style','Relaxation Focused'),(57,'interest','Beaches'),(57,'interest','Nightlife'),(57,'interest','Water Sports'),(57,'activity','Clubbing, beaches'),(57,'accommodation','Hotels & villas'),
(58,'style','Cultural Explorer'),(58,'style','Relaxation Focused'),(58,'interest','Beaches'),(58,'interest','Architecture'),(58,'interest','Food & Cuisine'),(58,'activity','City of Arts, beach'),(58,'accommodation','Hotels'),
(59,'style','Cultural Explorer'),(59,'interest','History'),(59,'interest','Architecture'),(59,'interest','Photography'),(59,'activity','Alhambra visits'),(59,'accommodation','Hotels'),
(60,'style','Cultural Explorer'),(60,'style','Relaxation Focused'),(60,'interest','Beaches'),(60,'interest','History'),(60,'interest','Photography'),(60,'activity','Old town walks, kayaking'),(60,'accommodation','Hotels'),
(61,'style','Relaxation Focused'),(61,'style','Cultural Explorer'),(61,'interest','Beaches'),(61,'interest','History'),(61,'interest','Nightlife'),(61,'activity','Island hopping'),(61,'accommodation','Hotels'),
(62,'style','Budget Backpacker'),(62,'style','Cultural Explorer'),(62,'interest','History'),(62,'interest','Architecture'),(62,'interest','Art & Museums'),(62,'activity','Old town tours'),(62,'accommodation','Hotels & hostels'),
(63,'style','Cultural Explorer'),(63,'interest','History'),(63,'interest','Architecture'),(63,'interest','Shopping'),(63,'activity','Museums, nightlife'),(63,'accommodation','Hotels'),
(64,'style','Cultural Explorer'),(64,'interest','History'),(64,'interest','Architecture'),(64,'interest','Photography'),(64,'activity','Medieval town visits'),(64,'accommodation','Hotels'),
(65,'style','Cultural Explorer'),(65,'interest','Architecture'),(65,'interest','History'),(65,'interest','Nightlife'),(65,'activity','Old town walks'),(65,'accommodation','Hotels'),
(66,'style','Cultural Explorer'),(66,'interest','History'),(66,'interest','Architecture'),(66,'interest','Art & Museums'),(66,'activity','Church tours'),(66,'accommodation','Hotels'),
(67,'style','Budget Backpacker'),(67,'style','Cultural Explorer'),(67,'interest','Architecture'),(67,'interest','History'),(67,'interest','Food & Cuisine'),(67,'activity','Cafe culture, old town'),(67,'accommodation','Hotels'),
(68,'style','Budget Backpacker'),(68,'style','Cultural Explorer'),(68,'interest','Food & Cuisine'),(68,'interest','History'),(68,'interest','Architecture'),(68,'activity','Wine tasting, old town'),(68,'accommodation','Guesthouses'),
(69,'style','Cultural Explorer'),(69,'style','Budget Backpacker'),(69,'interest','History'),(69,'interest','Architecture'),(69,'interest','Food & Cuisine'),(69,'activity','Museums, markets'),(69,'accommodation','Hotels'),
(70,'style','Cultural Explorer'),(70,'interest','Architecture'),(70,'interest','History'),(70,'interest','Shopping'),(70,'activity','Old city, modern skyline'),(70,'accommodation','Hotels'),
(71,'style','Luxury Traveler'),(71,'style','Cultural Explorer'),(71,'interest','Shopping'),(71,'interest','Architecture'),(71,'interest','Art & Museums'),(71,'activity','Museums, desert tours'),(71,'accommodation','Hotels'),
(72,'style','Adventure Seeker'),(72,'style','Relaxation Focused'),(72,'interest','Beaches'),(72,'interest','Desert'),(72,'interest','Mountains'),(72,'activity','Wadis, desert trips'),(72,'accommodation','Hotels'),
(73,'style','Budget Backpacker'),(73,'style','Adventure Seeker'),(73,'interest','Mountains'),(73,'interest','Hiking'),(73,'interest','History'),(73,'activity','Trekking, temples'),(73,'accommodation','Hostels'),
(74,'style','Cultural Explorer'),(74,'interest','Mountains'),(74,'interest','History'),(74,'interest','Photography'),(74,'activity','Monasteries'),(74,'accommodation','Hotels'),
(75,'style','Relaxation Focused'),(75,'style','Cultural Explorer'),(75,'interest','Beaches'),(75,'interest','Food & Cuisine'),(75,'interest','History'),(75,'activity','Markets, coastal tours'),(75,'accommodation','Hotels'),
(76,'style','Cultural Explorer'),(76,'interest','Mountains'),(76,'interest','History'),(76,'interest','Photography'),(76,'activity','Temple visits'),(76,'accommodation','Hotels'),
(77,'style','Cultural Explorer'),(77,'style','Budget Backpacker'),(77,'interest','History'),(77,'interest','Architecture'),(77,'interest','Photography'),(77,'activity','Pagodas, markets'),(77,'accommodation','Hotels'),
(78,'style','Relaxation Focused'),(78,'style','Cultural Explorer'),(78,'interest','Photography'),(78,'interest','History'),(78,'interest','Food & Cuisine'),(78,'activity','Waterfalls, temples'),(78,'accommodation','Boutique hotels'),
(79,'style','Cultural Explorer'),(79,'style','Adventure Seeker'),(79,'interest','History'),(79,'interest','Photography'),(79,'interest','Hiking'),(79,'activity','Angkor Wat tours'),(79,'accommodation','Hotels'),
(80,'style','Adventure Seeker'),(80,'interest','Mountains'),(80,'interest','Wildlife'),(80,'interest','Photography'),(80,'activity','Nomadic tours'),(80,'accommodation','Ger camps'),
(81,'style','Adventure Seeker'),(81,'interest','Mountains'),(81,'interest','Hiking'),(81,'interest','Photography'),(81,'activity','Skiing, hiking'),(81,'accommodation','Hotels'),
(82,'style','Cultural Explorer'),(82,'interest','Architecture'),(82,'interest','History'),(82,'interest','Shopping'),(82,'activity','Markets, mosques'),(82,'accommodation','Hotels'),
(83,'style','Cultural Explorer'),(83,'interest','Architecture'),(83,'interest','History'),(83,'interest','Photography'),(83,'activity','Registan tours'),(83,'accommodation','Hotels'),
(84,'style','Cultural Explorer'),(84,'interest','History'),(84,'interest','Food & Cuisine'),(84,'activity','Museums, markets'),(84,'accommodation','Hotels'),
(85,'style','Relaxation Focused'),(85,'interest','Beaches'),(85,'interest','Water Sports'),(85,'interest','Food & Cuisine'),(85,'activity','Snorkeling, beaches'),(85,'accommodation','Resorts'),
(86,'style','Adventure Seeker'),(86,'style','Luxury Traveler'),(86,'interest','Wildlife'),(86,'interest','Photography'),(86,'activity','Safari'),(86,'accommodation','Lodges'),
(87,'style','Adventure Seeker'),(87,'interest','Photography'),(87,'interest','Adventure'),(87,'activity','Falls, rafting'),(87,'accommodation','Hotels'),
(88,'style','Adventure Seeker'),(88,'interest','Desert'),(88,'interest','Photography'),(88,'interest','Wildlife'),(88,'activity','Dune exploration'),(88,'accommodation','Lodges'),
(89,'style','Adventure Seeker'),(89,'interest','Mountains'),(89,'interest','Hiking'),(89,'interest','Photography'),(89,'activity','Trekking, glaciers'),(89,'accommodation','Lodges'),
(90,'style','Cultural Explorer'),(90,'style','Adventure Seeker'),(90,'interest','History'),(90,'interest','Mountains'),(90,'interest','Photography'),(90,'activity','Ruins, trekking'),(90,'accommodation','Hotels'),
(91,'style','Cultural Explorer'),(91,'interest','Mountains'),(91,'interest','Food & Cuisine'),(91,'interest','Shopping'),(91,'activity','City tours, wine'),(91,'accommodation','Hotels'),
(92,'style','Cultural Explorer'),(92,'interest','Art & Museums'),(92,'interest','Photography'),(92,'interest','Architecture'),(92,'activity','Street art tours'),(92,'accommodation','Hotels'),
(93,'style','Cultural Explorer'),(93,'interest','History'),(93,'interest','Architecture'),(93,'interest','Photography'),(93,'activity','Old town tours'),(93,'accommodation','Hotels'),
(94,'style','Adventure Seeker'),(94,'style','Luxury Traveler'),(94,'interest','Wildlife'),(94,'interest','Water Sports'),(94,'interest','Photography'),(94,'activity','Diving, wildlife tours'),(94,'accommodation','Cruises & lodges'),
(95,'style','Adventure Seeker'),(95,'style','Budget Backpacker'),(95,'interest','Mountains'),(95,'interest','Photography'),(95,'activity','Cable cars, trekking'),(95,'accommodation','Hotels'),
(96,'style','Relaxation Focused'),(96,'interest','Beaches'),(96,'interest','Food & Cuisine'),(96,'activity','Coastal walks'),(96,'accommodation','Hotels'),
(97,'style','Luxury Traveler'),(97,'style','Relaxation Focused'),(97,'interest','Beaches'),(97,'interest','Nightlife'),(97,'activity','Beach clubs'),(97,'accommodation','Hotels'),
(98,'style','Adventure Seeker'),(98,'interest','Beaches'),(98,'interest','Photography'),(98,'interest','Wildlife'),(98,'activity','Hot springs, lava fields'),(98,'accommodation','Hotels'),
(99,'style','Adventure Seeker'),(99,'interest','Mountains'),(99,'interest','Photography'),(99,'interest','Hiking'),(99,'activity','Cliff hikes'),(99,'accommodation','Guesthouses'),
(100,'style','Adventure Seeker'),(100,'interest','Wildlife'),(100,'interest','Photography'),(100,'activity','Icebergs, expeditions'),(100,'accommodation','Lodges'),
(101,'style','Cultural Explorer'),(101,'style','Relaxation Focused'),(101,'interest','Architecture'),(101,'interest','History'),(101,'interest','Photography'),(101,'activity','Canal walks, museums'),(101,'accommodation','Hotels'),
(102,'style','Cultural Explorer'),(102,'interest','Architecture'),(102,'interest','History'),(102,'interest','Nightlife'),(102,'activity','Castle visits, nightlife'),(102,'accommodation','Hotels'),
(103,'style','Cultural Explorer'),(103,'interest','History'),(103,'interest','Architecture'),(103,'interest','Photography'),(103,'activity','Old town walks'),(103,'accommodation','Hotels'),
(104,'style','Adventure Seeker'),(104,'style','Relaxation Focused'),(104,'interest','Mountains'),(104,'interest','Shopping'),(104,'interest','Hiking'),(104,'activity','Skiing, shopping'),(104,'accommodation','Hotels'),
(105,'style','Adventure Seeker'),(105,'interest','Mountains'),(105,'interest','Hiking'),(105,'interest','Photography'),(105,'activity','Alpine sports'),(105,'accommodation','Chalets & hotels'),
(106,'style','Cultural Explorer'),(106,'interest','Food & Cuisine'),(106,'interest','Architecture'),(106,'interest','Photography'),(106,'activity','Wine tours'),(106,'accommodation','Hotels'),
(107,'style','Cultural Explorer'),(107,'interest','Food & Cuisine'),(107,'interest','History'),(107,'interest','Architecture'),(107,'activity','Gastronomy tours'),(107,'accommodation','Hotels'),
(108,'style','Relaxation Focused'),(108,'style','Cultural Explorer'),(108,'interest','Beaches'),(108,'interest','Food & Cuisine'),(108,'interest','History'),(108,'activity','Harbor walks, beaches'),(108,'accommodation','Hotels'),
(109,'style','Cultural Explorer'),(109,'interest','Food & Cuisine'),(109,'interest','History'),(109,'interest','Architecture'),(109,'activity','Pizza tours, ruins'),(109,'accommodation','Hotels'),
(110,'style','Luxury Traveler'),(110,'style','Cultural Explorer'),(110,'interest','Shopping'),(110,'interest','Architecture'),(110,'interest','Art & Museums'),(110,'activity','Fashion, museums'),(110,'accommodation','Hotels'),
(111,'style','Cultural Explorer'),(111,'interest','Architecture'),(111,'interest','History'),(111,'interest','Food & Cuisine'),(111,'activity','Museums, cafes'),(111,'accommodation','Hotels'),
(112,'style','Cultural Explorer'),(112,'style','Relaxation Focused'),(112,'interest','History'),(112,'interest','Architecture'),(112,'interest','Photography'),(112,'activity','Old town exploration'),(112,'accommodation','Boutique hotels'),
(113,'style','Cultural Explorer'),(113,'interest','Food & Cuisine'),(113,'interest','History'),(113,'interest','Architecture'),(113,'activity','Markets, beaches'),(113,'accommodation','Hotels'),
(114,'style','Cultural Explorer'),(114,'style','Relaxation Focused'),(114,'interest','History'),(114,'interest','Architecture'),(114,'interest','Beaches'),(114,'activity','Historic tours'),(114,'accommodation','Hotels'),
(115,'style','Adventure Seeker'),(115,'interest','Photography'),(115,'interest','Wildlife'),(115,'interest','Mountains'),(115,'activity','Golden Circle tours'),(115,'accommodation','Hotels'),
(116,'style','Cultural Explorer'),(116,'interest','Art & Museums'),(116,'interest','Architecture'),(116,'activity','Museums, fjords'),(116,'accommodation','Hotels'),
(117,'style','Adventure Seeker'),(117,'interest','Mountains'),(117,'interest','Photography'),(117,'activity','Fjord tours'),(117,'accommodation','Hotels'),
(118,'style','Cultural Explorer'),(118,'interest','Architecture'),(118,'interest','Art & Museums'),(118,'interest','Shopping'),(118,'activity','Saunas, design'),(118,'accommodation','Hotels'),
(119,'style','Relaxation Focused'),(119,'interest','Photography'),(119,'interest','Sauna'),(119,'activity','Lake activities'),(119,'accommodation','Hotels'),
(120,'style','Cultural Explorer'),(120,'interest','History'),(120,'interest','Architecture'),(120,'interest','Photography'),(120,'activity','Harbor walks'),(120,'accommodation','Hotels'),
(121,'style','Adventure Seeker'),(121,'style','Cultural Explorer'),(121,'interest','Mountains'),(121,'interest','History'),(121,'interest','Photography'),(121,'activity','Castle tours, hiking'),(121,'accommodation','Hotels'),
(122,'style','Cultural Explorer'),(122,'interest','Architecture'),(122,'interest','History'),(122,'interest','Nightlife'),(122,'activity','Museums, nightlife'),(122,'accommodation','Hotels'),
(123,'style','Budget Backpacker'),(123,'style','Cultural Explorer'),(123,'interest','History'),(123,'interest','Architecture'),(123,'activity','City tours'),(123,'accommodation','Hotels'),
(124,'style','Cultural Explorer'),(124,'interest','Nightlife'),(124,'interest','History'),(124,'interest','Food & Cuisine'),(124,'activity','Clubs, river cruises'),(124,'accommodation','Hotels'),
(125,'style','Cultural Explorer'),(125,'interest','History'),(125,'interest','Food & Cuisine'),(125,'interest','Architecture'),(125,'activity','Old bazaar visits'),(125,'accommodation','Hotels'),
(126,'style','Cultural Explorer'),(126,'interest','Architecture'),(126,'interest','History'),(126,'activity','Statue tours'),(126,'accommodation','Hotels'),
(127,'style','Relaxation Focused'),(127,'interest','Photography'),(127,'interest','Mountains'),(127,'activity','Nature trips'),(127,'accommodation','Hotels'),
(128,'style','Cultural Explorer'),(128,'style','Relaxation Focused'),(128,'interest','Beaches'),(128,'interest','Mountains'),(128,'interest','Photography'),(128,'activity','Bay cruises'),(128,'accommodation','Hotels'),
(129,'style','Budget Backpacker'),(129,'style','Cultural Explorer'),(129,'interest','History'),(129,'interest','Food & Cuisine'),(129,'activity','City tours'),(129,'accommodation','Hotels'),
(130,'style','Cultural Explorer'),(130,'interest','Beaches'),(130,'interest','History'),(130,'interest','Food & Cuisine'),(130,'activity','Markets, coast'),(130,'accommodation','Hotels'),
(131,'style','Cultural Explorer'),(131,'interest','Beaches'),(131,'interest','Food & Cuisine'),(131,'activity','Island visits'),(131,'accommodation','Hotels'),
(132,'style','Cultural Explorer'),(132,'interest','Nightlife'),(132,'interest','Food & Cuisine'),(132,'activity','Clubs, markets'),(132,'accommodation','Hotels'),
(133,'style','Adventure Seeker'),(133,'interest','Wildlife'),(133,'interest','Photography'),(133,'activity','Safari, parks'),(133,'accommodation','Hotels'),
(134,'style','Relaxation Focused'),(134,'interest','Beaches'),(134,'interest','Water Sports'),(134,'activity','Beach resorts'),(134,'accommodation','Resorts'),
(135,'style','Adventure Seeker'),(135,'interest','Wildlife'),(135,'interest','Photography'),(135,'activity','Nature tours'),(135,'accommodation','Hotels'),
(136,'style','Adventure Seeker'),(136,'interest','Wildlife'),(136,'interest','Desert'),(136,'interest','Photography'),(136,'activity','Safari tours'),(136,'accommodation','Hotels'),
(137,'style','Relaxation Focused'),(137,'interest','Beaches'),(137,'interest','Photography'),(137,'activity','Beach life'),(137,'accommodation','Hotels'),
(138,'style','Cultural Explorer'),(138,'interest','Food & Cuisine'),(138,'interest','Beaches'),(138,'activity','Wine regions'),(138,'accommodation','Hotels'),
(139,'style','Adventure Seeker'),(139,'interest','Wildlife'),(139,'interest','Beaches'),(139,'activity','National parks'),(139,'accommodation','Hotels'),
(140,'style','Cultural Explorer'),(140,'interest','Art & Museums'),(140,'interest','Food & Cuisine'),(140,'activity','Museums, markets'),(140,'accommodation','Hotels'),
(141,'style','Relaxation Focused'),(141,'interest','Beaches'),(141,'interest','Water Sports'),(141,'activity','Island tours'),(141,'accommodation','Resorts'),
(142,'style','Relaxation Focused'),(142,'interest','Beaches'),(142,'interest','Water Sports'),(142,'interest','Photography'),(142,'activity','Snorkeling'),(142,'accommodation','Resorts'),
(143,'style','Adventure Seeker'),(143,'interest','Water Sports'),(143,'interest','Wildlife'),(143,'activity','Diving, volcano tours'),(143,'accommodation','Resorts'),
(144,'style','Luxury Traveler'),(144,'style','Relaxation Focused'),(144,'interest','Beaches'),(144,'interest','Food & Cuisine'),(144,'activity','Lagoon activities'),(144,'accommodation','Hotels'),
(145,'style','Adventure Seeker'),(145,'interest','Wildlife'),(145,'interest','Mountains'),(145,'interest','Photography'),(145,'activity','Glaciers, hiking'),(145,'accommodation','Hotels'),
(146,'style','Adventure Seeker'),(146,'interest','Wildlife'),(146,'interest','Photography'),(146,'activity','Whale watching'),(146,'accommodation','Hotels'),
(147,'style','Cultural Explorer'),(147,'interest','History'),(147,'interest','Architecture'),(147,'interest','Food & Cuisine'),(147,'activity','Old town tours'),(147,'accommodation','Hotels'),
(148,'style','Cultural Explorer'),(148,'interest','History'),(148,'interest','Food & Cuisine'),(148,'activity','Harbor walks'),(148,'accommodation','Hotels'),
(149,'style','Cultural Explorer'),(149,'interest','Art & Museums'),(149,'interest','History'),(149,'activity','Museums'),(149,'accommodation','Hotels'),
(150,'style','Adventure Seeker'),(150,'style','Cultural Explorer'),(150,'interest','Mountains'),(150,'interest','Hiking'),(150,'interest','Art & Museums'),(150,'activity','Hiking, breweries'),(150,'accommodation','Hotels & cabins'),
(151,'style','Adventure Seeker'),(151,'style','Relaxation Focused'),(151,'interest','Mountains'),(151,'interest','Hiking'),(151,'interest','Photography'),(151,'activity','Hiking, wellness'),(151,'accommodation','Resorts'),
(152,'style','Cultural Explorer'),(152,'interest','Art & Museums'),(152,'interest','Architecture'),(152,'interest','Food & Cuisine'),(152,'activity','Galleries, cuisine'),(152,'accommodation','Hotels'),
(153,'style','Cultural Explorer'),(153,'interest','Nightlife'),(153,'interest','Food & Cuisine'),(153,'activity','Live music, bars'),(153,'accommodation','Hotels'),
(154,'style','Cultural Explorer'),(154,'interest','Food & Cuisine'),(154,'interest','Nightlife'),(154,'interest','Art & Museums'),(154,'activity','Food trucks, music'),(154,'accommodation','Hotels'),
(155,'style','Cultural Explorer'),(155,'style','Relaxation Focused'),(155,'interest','Architecture'),(155,'interest','History'),(155,'interest','Photography'),(155,'activity','Historic walks'),(155,'accommodation','Boutique hotels'),
(156,'style','Cultural Explorer'),(156,'style','Relaxation Focused'),(156,'interest','History'),(156,'interest','Architecture'),(156,'interest','Food & Cuisine'),(156,'activity','Historic tours'),(156,'accommodation','Hotels'),
(157,'style','Relaxation Focused'),(157,'interest','Beaches'),(157,'interest','Water Sports'),(157,'interest','Nightlife'),(157,'activity','Beach, nightlife'),(157,'accommodation','Hotels'),
(158,'style','Cultural Explorer'),(158,'style','Relaxation Focused'),(158,'interest','Beaches'),(158,'interest','History'),(158,'interest','Architecture'),(158,'activity','Old town, beaches'),(158,'accommodation','Hotels'),
(159,'style','Cultural Explorer'),(159,'interest','Nightlife'),(159,'interest','Food & Cuisine'),(159,'interest','Art & Museums'),(159,'activity','City tours'),(159,'accommodation','Hotels'),
(160,'style','Cultural Explorer'),(160,'interest','Beaches'),(160,'interest','History'),(160,'interest','Food & Cuisine'),(160,'activity','Historic center'),(160,'accommodation','Hotels'),
(161,'style','Relaxation Focused'),(161,'interest','Beaches'),(161,'interest','Water Sports'),(161,'activity','Surfing, beaches'),(161,'accommodation','Hotels'),
(162,'style','Relaxation Focused'),(162,'interest','Beaches'),(162,'interest','Water Sports'),(162,'activity','Resorts, snorkeling'),(162,'accommodation','Resorts'),
(163,'style','Cultural Explorer'),(163,'interest','History'),(163,'interest','Architecture'),(163,'interest','Photography'),(163,'activity','Classic cars, music'),(163,'accommodation','Guesthouses'),
(164,'style','Adventure Seeker'),(164,'interest','Wildlife'),(164,'interest','Hiking'),(164,'interest','Mountains'),(164,'activity','Rainforest tours'),(164,'accommodation','Hotels'),
(165,'style','Cultural Explorer'),(165,'interest','Shopping'),(165,'interest','History'),(165,'interest','Architecture'),(165,'activity','Canal visits'),(165,'accommodation','Hotels'),
(166,'style','Budget Backpacker'),(166,'style','Cultural Explorer'),(166,'interest','History'),(166,'interest','Food & Cuisine'),(166,'activity','Markets, museums'),(166,'accommodation','Hotels'),
(167,'style','Cultural Explorer'),(167,'interest','Architecture'),(167,'interest','History'),(167,'interest','Photography'),(167,'activity','Volcano hikes'),(167,'accommodation','Boutique hotels'),
(168,'style','Cultural Explorer'),(168,'interest','Shopping'),(168,'interest','Nightlife'),(168,'interest','Food & Cuisine'),(168,'activity','City tours'),(168,'accommodation','Hotels'),
(169,'style','Adventure Seeker'),(169,'interest','Beaches'),(169,'interest','Water Sports'),(169,'interest','Wildlife'),(169,'activity','Diving, waterfalls'),(169,'accommodation','Hotels'),
(170,'style','Relaxation Focused'),(170,'interest','Beaches'),(170,'interest','Water Sports'),(170,'interest','Nightlife'),(170,'activity','Beach activities'),(170,'accommodation','Resorts'),
(171,'style','Cultural Explorer'),(171,'interest','Food & Cuisine'),(171,'activity','Snow festival, skiing'),(171,'accommodation','Hotels'),
(172,'style','Cultural Explorer'),(172,'interest','Food & Cuisine'),(172,'interest','Shopping'),(172,'activity','Street food'),(172,'accommodation','Hotels'),
(173,'style','Relaxation Focused'),(173,'interest','Beaches'),(173,'interest','Food & Cuisine'),(173,'interest','Shopping'),(173,'activity','Beach, seafood'),(173,'accommodation','Hotels'),
(174,'style','Relaxation Focused'),(174,'interest','Beaches'),(174,'interest','Water Sports'),(174,'activity','Beach resorts'),(174,'accommodation','Hotels'),
(175,'style','Cultural Explorer'),(175,'style','Adventure Seeker'),(175,'interest','Mountains'),(175,'interest','Food & Cuisine'),(175,'activity','Temples, trekking'),(175,'accommodation','Hotels'),
(176,'style','Cultural Explorer'),(176,'interest','Food & Cuisine'),(176,'interest','Art & Museums'),(176,'interest','Architecture'),(176,'activity','Street food'),(176,'accommodation','Hotels'),
(177,'style','Cultural Explorer'),(177,'interest','Shopping'),(177,'interest','Food & Cuisine'),(177,'interest','Architecture'),(177,'activity','City tours'),(177,'accommodation','Hotels'),
(178,'style','Cultural Explorer'),(178,'interest','Shopping'),(178,'interest','Nightlife'),(178,'interest','Food & Cuisine'),(178,'activity','Markets, nightlife'),(178,'accommodation','Hotels'),
(179,'style','Cultural Explorer'),(179,'interest','History'),(179,'interest','Architecture'),(179,'interest','Photography'),(179,'activity','Temple visits'),(179,'accommodation','Hotels'),
(180,'style','Cultural Explorer'),(180,'interest','History'),(180,'interest','Architecture'),(180,'interest','Art & Museums'),(180,'activity','Museums, bazaars'),(180,'accommodation','Hotels'),
(181,'style','Cultural Explorer'),(181,'interest','Architecture'),(181,'interest','History'),(181,'interest','Photography'),(181,'activity','Mosques, squares'),(181,'accommodation','Hotels'),
(182,'style','Cultural Explorer'),(182,'interest','History'),(182,'interest','Architecture'),(182,'activity','Gardens, ruins'),(182,'accommodation','Hotels'),
(183,'style','Cultural Explorer'),(183,'interest','History'),(183,'interest','Food & Cuisine'),(183,'activity','Roman ruins'),(183,'accommodation','Hotels'),
(184,'style','Cultural Explorer'),(184,'style','Nightlife'),(184,'interest','Nightlife'),(184,'interest','Food & Cuisine'),(184,'interest','History'),(184,'activity','Clubs, food'),(184,'accommodation','Hotels'),
(185,'style','Cultural Explorer'),(185,'interest','History'),(185,'interest','Architecture'),(185,'activity','Medina tours'),(185,'accommodation','Hotels'),
(186,'style','Cultural Explorer'),(186,'interest','Architecture'),(186,'interest','History'),(186,'activity','City tours'),(186,'accommodation','Hotels'),
(187,'style','Relaxation Focused'),(187,'interest','Beaches'),(187,'interest','Water Sports'),(187,'activity','Beach relaxation'),(187,'accommodation','Resorts'),
(188,'style','Luxury Traveler'),(188,'style','Relaxation Focused'),(188,'interest','Beaches'),(188,'interest','Water Sports'),(188,'interest','Photography'),(188,'activity','Snorkeling'),(188,'accommodation','Luxury resorts'),
(189,'style','Luxury Traveler'),(189,'style','Relaxation Focused'),(189,'interest','Beaches'),(189,'interest','Water Sports'),(189,'activity','Resorts, diving'),(189,'accommodation','Resorts'),
(190,'style','Adventure Seeker'),(190,'interest','Wildlife'),(190,'interest','Photography'),(190,'activity','Geysers, culture'),(190,'accommodation','Hotels'),
(191,'style','Cultural Explorer'),(191,'interest','Architecture'),(191,'activity','City tours'),(191,'accommodation','Hotels'),
(192,'style','Adventure Seeker'),(192,'interest','Mountains'),(192,'interest','Hiking'),(192,'activity','Winter sports'),(192,'accommodation','Hotels'),
(193,'style','Luxury Traveler'),(193,'style','Cultural Explorer'),(193,'interest','Shopping'),(193,'interest','Food & Cuisine'),(193,'activity','Lake activities'),(193,'accommodation','Hotels'),
(194,'style','Relaxation Focused'),(194,'style','Cultural Explorer'),(194,'interest','Food & Cuisine'),(194,'interest','Photography'),(194,'activity','Lake walks'),(194,'accommodation','Hotels'),
(195,'style','Cultural Explorer'),(195,'interest','Art & Museums'),(195,'interest','Architecture'),(195,'activity','Museums'),(195,'accommodation','Hotels'),
(196,'style','Luxury Traveler'),(196,'style','Cultural Explorer'),(196,'interest','Shopping'),(196,'interest','Food & Cuisine'),(196,'activity','City tours'),(196,'accommodation','Hotels'),
(197,'style','Cultural Explorer'),(197,'style','Relaxation Focused'),(197,'interest','Architecture'),(197,'interest','Photography'),(197,'interest','Food & Cuisine'),(197,'activity','Old town, river'),(197,'accommodation','Hotels'),
(198,'style','Relaxation Focused'),(198,'interest','Mountains'),(198,'interest','Photography'),(198,'activity','Lake walks'),(198,'accommodation','Hotels'),
(199,'style','Cultural Explorer'),(199,'interest','Architecture'),(199,'interest','History'),(199,'interest','Photography'),(199,'activity','Bridge visits'),(199,'accommodation','Hotels'),
(200,'style','Cultural Explorer'),(200,'interest','History'),(200,'interest','Art & Museums'),(200,'interest','Food & Cuisine'),(200,'activity','City tours, museums'),(200,'accommodation','Hotels'),
(201,'style','Relaxation Focused'),(201,'interest','Beaches'),(201,'interest','Photography'),(201,'activity','Lake Kivu relaxation'),(201,'accommodation','Hotels'),
(202,'style','Relaxation Focused'),(202,'style','Cultural Explorer'),(202,'interest','Beaches'),(202,'interest','Food & Cuisine'),(202,'activity','Lake activities'),(202,'accommodation','Hotels'),
(203,'style','Budget Backpacker'),(203,'style','Cultural Explorer'),(203,'interest','Wildlife'),(203,'activity','Local markets, safaris'),(203,'accommodation','Hotels'),
(204,'style','Cultural Explorer'),(204,'interest','Beaches'),(204,'interest','Food & Cuisine'),(204,'interest','Architecture'),(204,'activity','City tours, coast'),(204,'accommodation','Hotels'),
(205,'style','Adventure Seeker'),(205,'interest','Beaches'),(205,'interest','Wildlife'),(205,'interest','Hiking'),(205,'activity','Surfing, whale watching'),(205,'accommodation','Lodges'),
(206,'style','Adventure Seeker'),(206,'style','Luxury Traveler'),(206,'interest','Mountains'),(206,'interest','Hiking'),(206,'activity','Skiing, biking'),(206,'accommodation','Resorts'),
(207,'style','Adventure Seeker'),(207,'interest','Mountains'),(207,'interest','Hiking'),(207,'interest','Photography'),(207,'activity','National park tours'),(207,'accommodation','Lodges'),
(208,'style','Adventure Seeker'),(208,'style','Relaxation Focused'),(208,'interest','Mountains'),(208,'interest','Hiking'),(208,'interest','Photography'),(208,'activity','Hiking, nature'),(208,'accommodation','Hotels'),
(209,'style','Adventure Seeker'),(209,'interest','Wildlife'),(209,'interest','Photography'),(209,'interest','Mountains'),(209,'activity','Northern lights'),(209,'accommodation','Hotels'),
(210,'style','Adventure Seeker'),(210,'interest','Wildlife'),(210,'interest','Photography'),(210,'activity','Santa village, snowmobiling'),(210,'accommodation','Hotels'),
(211,'style','Adventure Seeker'),(211,'interest','Wildlife'),(211,'interest','Photography'),(211,'activity','Ice fjords, hiking'),(211,'accommodation','Hotels'),
(212,'style','Adventure Seeker'),(212,'interest','Wildlife'),(212,'interest','Photography'),(212,'activity','Polar tours'),(212,'accommodation','Lodges'),
(213,'style','Adventure Seeker'),(213,'style','Relaxation Focused'),(213,'interest','Mountains'),(213,'interest','Photography'),(213,'activity','Hiking, whale watching'),(213,'accommodation','Hotels'),
(214,'style','Adventure Seeker'),(214,'style','Relaxation Focused'),(214,'interest','Mountains'),(214,'interest','Hiking'),(214,'interest','Photography'),(214,'activity','Levadas hikes'),(214,'accommodation','Hotels'),
(215,'style','Adventure Seeker'),(215,'style','Relaxation Focused'),(215,'interest','Beaches'),(215,'interest','Mountains'),(215,'interest','Hiking'),(215,'activity','Beach + hiking'),(215,'accommodation','Hotels'),
(216,'style','Relaxation Focused'),(216,'style','Luxury Traveler'),(216,'interest','Beaches'),(216,'interest','Water Sports'),(216,'activity','Beach relaxation'),(216,'accommodation','Resorts'),
(217,'style','Relaxation Focused'),(217,'interest','Beaches'),(217,'interest','Photography'),(217,'activity','Coves, relaxation'),(217,'accommodation','Hotels'),
(218,'style','Relaxation Focused'),(218,'style','Adventure Seeker'),(218,'interest','Beaches'),(218,'interest','Hiking'),(218,'interest','Mountains'),(218,'activity','Cycling, beaches'),(218,'accommodation','Hotels'),
(219,'style','Relaxation Focused'),(219,'interest','Beaches'),(219,'interest','Nightlife'),(219,'interest','Food & Cuisine'),(219,'activity','Beach parties'),(219,'accommodation','Hotels'),
(220,'style','Relaxation Focused'),(220,'interest','Food & Cuisine'),(220,'interest','Wildlife'),(220,'activity','Backwaters cruises'),(220,'accommodation','Hotels'),
(221,'style','Cultural Explorer'),(221,'interest','History'),(221,'interest','Architecture'),(221,'interest','Shopping'),(221,'activity','Palaces, markets'),(221,'accommodation','Hotels'),
(222,'style','Cultural Explorer'),(222,'style','Relaxation Focused'),(222,'interest','Architecture'),(222,'interest','Photography'),(222,'activity','Lake palaces'),(222,'accommodation','Hotels'),
(223,'style','Cultural Explorer'),(223,'interest','Food & Cuisine'),(223,'interest','History'),(223,'interest','Architecture'),(223,'activity','Food tours'),(223,'accommodation','Hotels'),
(224,'style','Cultural Explorer'),(224,'interest','Beaches'),(224,'interest','Food & Cuisine'),(224,'interest','Nightlife'),(224,'activity','City tours'),(224,'accommodation','Hotels'),
(225,'style','Budget Backpacker'),(225,'style','Cultural Explorer'),(225,'interest','History'),(225,'activity','City exploration'),(225,'accommodation','Hotels'),
(226,'style','Adventure Seeker'),(226,'style','Cultural Explorer'),(226,'interest','Mountains'),(226,'interest','History'),(226,'interest','Hiking'),(226,'activity','Temples, trekking'),(226,'accommodation','Hotels'),
(227,'style','Cultural Explorer'),(227,'interest','Mountains'),(227,'interest','History'),(227,'interest','Photography'),(227,'activity','Tiger''s Nest hike'),(227,'accommodation','Hotels'),
(228,'style','Cultural Explorer'),(228,'interest','History'),(228,'interest','Mountains'),(228,'interest','Photography'),(228,'activity','Monasteries'),(228,'accommodation','Hotels'),
(229,'style','Cultural Explorer'),(229,'interest','Food & Cuisine'),(229,'interest','Wildlife'),(229,'activity','Panda reserves'),(229,'accommodation','Hotels'),
(230,'style','Adventure Seeker'),(230,'interest','Mountains'),(230,'interest','Photography'),(230,'activity','River cruises'),(230,'accommodation','Hotels'),
(231,'style','Adventure Seeker'),(231,'interest','Mountains'),(231,'interest','Hiking'),(231,'interest','Photography'),(231,'activity','National park hikes'),(231,'accommodation','Hotels'),
(232,'style','Cultural Explorer'),(232,'interest','Architecture'),(232,'interest','Photography'),(232,'activity','Ice festival'),(232,'accommodation','Hotels'),
(233,'style','Adventure Seeker'),(233,'interest','Mountains'),(233,'interest','Wildlife'),(233,'activity','Antarctic gateway'),(233,'accommodation','Hotels'),
(234,'style','Adventure Seeker'),(234,'interest','Mountains'),(234,'interest','Hiking'),(234,'interest','Photography'),(234,'activity','Lakes, hiking'),(234,'accommodation','Hotels'),
(235,'style','Cultural Explorer'),(235,'interest','Food & Cuisine'),(235,'interest','Mountains'),(235,'activity','Wine tours'),(235,'accommodation','Hotels'),
(236,'style','Adventure Seeker'),(236,'style','Cultural Explorer'),(236,'interest','Mountains'),(236,'interest','History'),(236,'interest','Hiking'),(236,'activity','Inca trails'),(236,'accommodation','Hotels'),
(237,'style','Cultural Explorer'),(237,'interest','Architecture'),(237,'interest','History'),(237,'activity','City tours'),(237,'accommodation','Hotels'),
(238,'style','Relaxation Focused'),(238,'interest','Beaches'),(238,'interest','Photography'),(238,'activity','Beach relaxation'),(238,'accommodation','Hotels'),
(239,'style','Adventure Seeker'),(239,'interest','Mountains'),(239,'interest','Water Sports'),(239,'interest','Hiking'),(239,'activity','Volcano climbs'),(239,'accommodation','Hotels'),
(240,'style','Cultural Explorer'),(240,'interest','Architecture'),(240,'interest','History'),(240,'activity','Old town tours'),(240,'accommodation','Hotels'),
(241,'style','Cultural Explorer'),(241,'interest','History'),(241,'activity','Carnival'),(241,'accommodation','Hotels'),
(242,'style','Cultural Explorer'),(242,'interest','History'),(242,'interest','Food & Cuisine'),(242,'activity','City tours'),(242,'accommodation','Hotels'),
(243,'style','Relaxation Focused'),(243,'interest','Beaches'),(243,'interest','Water Sports'),(243,'activity','Beach life'),(243,'accommodation','Hotels'),
(244,'style','Relaxation Focused'),(244,'style','Nightlife'),(244,'interest','Beaches'),(244,'interest','Nightlife'),(244,'activity','Beach parties'),(244,'accommodation','Hotels'),
(245,'style','Relaxation Focused'),(245,'interest','Beaches'),(245,'interest','Photography'),(245,'activity','Dunes, beaches'),(245,'accommodation','Hotels'),
(246,'style','Luxury Traveler'),(246,'style','Relaxation Focused'),(246,'interest','Beaches'),(246,'interest','Water Sports'),(246,'activity','Resorts'),(246,'accommodation','Resorts'),
(247,'style','Relaxation Focused'),(247,'interest','Beaches'),(247,'interest','Architecture'),(247,'interest','Water Sports'),(247,'activity','Diving'),(247,'accommodation','Hotels'),
(248,'style','Adventure Seeker'),(248,'interest','Water Sports'),(248,'interest','Wildlife'),(248,'activity','Diving'),(248,'accommodation','Hotels');

